### ISSUE TITLE
Small Changes

### ISSUE THREAD

**Issue by ThomasThelen** [nateshmbhat/snakes#1]
<h1>Take out `using namsepsace std`</h1>

See https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice

<h1>Get Rid of the Global Variables</h1>
You should never have global variables in your program. The colors can be defined in an enum. But be sure to use a scoped enum. The class declarations can be put in the main function. If you need them in a function, pass it by reference. 

<h1>Take String Arguments by const ref When Possible</h1>
 Game::printAnimated(string msg , int speed)
can be written as 
 Game::printAnimated(const string& msg , int speed)

In the first way, the compiler copies the value that you passed to the function into msg. Since you don't actually modify msg at all, there's no point in having a copy of it. The second way passes the memory address of the string, so it avoids expensive memory allocations. This can be done in a few other functions.

<h1>Use the auto keyword</h1>
http://www.learncpp.com/cpp-tutorial/4-8-the-auto-keyword/

**Comment by nateshmbhat** [comment]
Thanks so much for posting this :)
